#include <script.hpp>

const std::unordered_map<std::string, db::script::OperationType> db::script::operators = {
	{"+", ADD},
	{"-", SUB},
	{"*", MUL},
	{"/", DIV},
	{"^", POW},
	{"%", MOD},
	{"==", EQUALS},
	{"!=", NEQUALS},
	{">", GREATER},
	{"<", LESS},
	{">=", GREATEREQUALS},
	{"<=", LESSEQUALS},
	{"||", OR},
	{"&&", AND},
	{"!", NOT},
	{"(", FUNC_PARAM_START},
	{")", FUNC_PARAM_END},
	{",", FUNC_PARAM_DELIMITER},
};

const std::unordered_map<db::script::OperationType, uint8_t> db::script::operator_precedence = {
	{ADD, 4},
	{SUB, 4},
	{MUL, 3},
	{DIV, 3},
	{MOD, 3},
	{POW, 2},
	{EQUALS, 7},
	{NEQUALS, 7},
	{GREATER, 6},
	{LESS, 6},
	{GREATEREQUALS, 6},
	{LESSEQUALS, 6},
	{OR, 12},
	{AND, 11},
	{NOT, 2},
	{FUNC_PARAM_START, 0},
	{FUNC_PARAM_END, 0},
	{FUNC_PARAM_DELIMITER, 0},
};